# Generated by Django 4.2.7 on 2023-11-10 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('acef5481-8951-426f-ab87-91e78a5eaeee'), primary_key=True, serialize=False)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
